#
# Blacklist packagegroups
#
INHERIT += "blacklist"
PNBLACKLIST[packagegroup-custom-full] = "does not fit in hd-1 flash memory."
PNBLACKLIST[packagegroup-custom-dev-utils] = "does not fit in hd-1 flash memory."
PNBLACKLIST[packagegroup-custom-extended] = "does not fit in hd-1 flash memory."
PNBLACKLIST[packagegroup-custom-libs] = "does not fit in hd-1 flash memory."
PNBLACKLIST[packagegroup-custom-multiuser] = "does not fit in hd-1 flash memory."
PNBLACKLIST[packagegroup-custom-sys-services] = "does not fit in hd-1 flash memory."
PNBLACKLIST[packagegroup-custom-utils] = "does not fit in hd-1 flash memory."
PNBLACKLIST[packagegroup-custom-recommended] = "does not fit in hd-1 flash memory."

